name: frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.0
  indexed: ^0.0.8
  flutter_colorpicker: ^1.0.3
  provider: ^6.1.2
  assets_audio_player: ^3.1.1
  flutter_styled_toast: ^2.2.1
  http: ^0.13.5
  shared_preferences: ^2.1.1
  cached_network_image: ^3.3.1
  transparent_image: ^2.0.1
  file_picker: ^6.2.0
  intl: ^0.18.1
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.0
  image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  camera: ^0.10.5+9
  tflite_v2: ^1.0.0
  flutter_dotenv: ^5.1.0
  bootpay: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/icons/
     - assets/fonts/
     - assets/music/
     - assets/tflite/
     - assets/config/

  fonts:
     - family: Nanumson_jangmi
       fonts:
         - asset: assets/fonts/Nanumson_jangmi.ttf
     - family: Itim
       fonts:
         - asset: assets/fonts/Itim-Regular.ttf
     - family: Varela
       fonts:
         - asset: assets/fonts/VarelaRound-Regular.ttf
     - family: Neucha
       fonts:
         - asset: assets/fonts/Neucha-Regular.ttf
     - family: PatrickHand
       fonts:
         - asset: assets/fonts/PatrickHand-Regular.ttf

