spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ssafyrds.cjw2k0eykv8p.ap-northeast-2.rds.amazonaws.com:3306/backend?serverTimezone=Asia/Seoul
    username: c204
    password: c204ssafy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: j10c101.p.ssafy.io
      port: 6379
      password: ssafy1234
      repositories:
        enabled: false
  servlet:
    multipart:
      max-file-size: 20MB


jwt:
  secret: 74744906e7fb955f341690a49787fc17fd5bd846e5b11cbc3f562dc1e828d5d104e1ce7472f4e4cafafa93628cc46cc71ed24fd3f2d86359bd9884066c5e3f95
  expired-min:
    access: 60   # access token 만료제한시간 60분 (1시간)
    refresh: 10080  # refresh token 만료제한시간 10080분 (7일)

logging:
  level:
    com:
      ssafy: debug
    root: info

cloud:
  aws:
    s3:
      bucket: donggle
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIARI2J3RH4QEK7CPSB
      secretKey: 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